<?php

/**
 * Implements hook_ting_client_webservice (@see ting_client.module)
 * */
function bibdk_navfors_ting_client_webservice() {
  $ret = array();
  $ret['navfors']['class'] = 'bibdk_navfors';
  $ret['navfors']['url'] = 'bibdk_navfors_url';
  $ret['navfors']['xsdNamespace'] = array(0=>'http://oss.dbc.dk/ns/forsrights');

  return $ret;
}

function bibdk_navfors_get_library_list ($serviceName) {
  $xml = bibdk_navfors_request($serviceName);
  return bibdk_navfors_parse_response($xml);
}

function bibdk_navfors_parse_response($xml){
  $dom = new DomDocument();
    if (!@$dom->loadXML($xml)) {
      if ( BibdkClient::$enable_logging ) {
        watchdog('bibdk_provider', t('BIBDK client could not load response: %xml', array('%xml' => var_export($xml, TRUE))), array(), WATCHDOG_ERROR);
      }
      return FALSE;
    }
    $xpath = new DomXPATH($dom);

    $query = '//customer';
    $nodelist = $xpath->query($query);
    foreach ($nodelist as $node) {
      $ret[] = $node->nodeValue;
    }

    return $ret;
}

/**
 * do a request
 * */
function bibdk_navfors_request($serviceName, $outputType = 'xml') {
  $client = new ting_client_class();
  // this is the real request
  $response = $client->do_request('navfors', array('serviceName' => $serviceName,'outputType' => $outputType,));
  return $response;
}

/**
 * Implements hook_form_FORM_ID_alter (ting_client_admin_webservices_settings)
 * add 2 fields to webservice client settings
 * @url to borchk
 * @servicerequester
 * */
function bibdk_navfors_form_ting_client_admin_webservices_settings_alter(&$form, &$form_state) {
  $form['ting']['bibdk_navfors_url'] = array(
    '#type' => 'textfield',
    '#title' => t('navfors URL'),
    '#description' => t('URL to navfors e.g. http://guesstimate.dbc.dk/~pjo/webservices/navfors/trunk/server.php'),
    '#required' => TRUE,
    '#default_value' => variable_get('bibdk_navfors_url', FALSE),
  );
}

/**
 * @return Array
 */
function bibdk_navfors_how_r_u() {
  return array('navfors' => variable_get('bibdk_navfors_url'));
}
