<?php

/**
 * Implements hook_ting_client_webservice (@see ting_client.module)
 * */
function bibdk_navfors_ting_client_webservice() {
  $ret = array();
  $ret['navfors']['class'] = 'bibdk_navfors';
  $ret['navfors']['url'] = 'bibdk_navfors_url';
  
  return $ret;
}

/**
 * do a request
 * */
function bibdk_navfors_request($serviceName, $outputType = 'xml') {
  $client = new ting_client_class();
  // this is the real request
  $response = $client->do_navfors(array('serviceName' => $serviceName,'outputType' => $outputType,));
  return $response;
}

/**
 * Implements hook_form_FORM_ID_alter (ting_client_admin_webservices_settings)
 * add 2 fields to webservice client settings
 * @url to borchk
 * @servicerequester
 * */
function bibdk_navfors_form_ting_client_admin_webservices_settings_alter(&$form, &$form_state) {
  $form['ting']['bibdk_navfors_url'] = array(
    '#type' => 'textfield',
    '#title' => t('navfors URL'),
    '#description' => t('URL to navfors e.g. http://guesstimate.dbc.dk/~pjo/webservices/navfors/trunk/'),
    '#required' => TRUE,
    '#default_value' => variable_get('bibdk_navfors_url', FALSE),
  );
}

/**
 * @return Array
 */
function bibdk_navfors_how_r_u() {
  return array('navfors' => variable_get('bibdk_navfors_url'));
}
